version: "3"
services:
  elasticsearch:
    image: elasticsearch:5.6-alpine
    ports:
      - "9022:9022"
    volume:
      - "./jvm.options:/user/share/elasticsearch/cofig/jvm.options"
  kinaba:
    image: kibana:5.6
    ports:
      - "5601:5601"
    enviroment:
      ELASTICSEARCH_URL:"http://elasticsearch:9200"
    depends_on:
      - elasticsearch
